using System.Collections.Generic;
using System.Web.Mvc;
using Gift.Core.EntityParams;
using Gift.Data.Models;

namespace Gift.Web.Areas.Dashboard.ViewModel {
    public class CityViewModel : CityParams {
        public IEnumerable<SelectListItem> CulturedCitySelectList { get; set; }
        public CityViewModel() {
            
        }

        public CityViewModel(Status status, bool isAutoGenerated = true) {
            Status = status;
            IsAutoGenerated = isAutoGenerated;
        }
    }
}